- README.md
> Cambios Santi

- client/.gitignore
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Landing.jsx
- client/src/index.js
> Git Ignore

- api/models/Pet.js
Agrego la propiedad 'sexo' en el modelo Pet.
> Agrego propiedad sexo en Pet

- client/src/App.js
- client/src/components/AllCards/AllCards.jsx
- client/src/components/CardDetail/CardDetail.jsx
Agregue dispatch en allCards para que muestre las cards que se hacen a partir de las rutas del back.
Solucione unos conflictos que habia en los componentes de Home y en CardDetail.
> Actualizacio front

- README.md
- api/db.js
- client/src/App.js
- client/src/components/NotFound/NotFound.jsx
+ Página no encontrada.
+ Componente para página no encontrada.
Faltan: Estilos al componente (soy malo con css y no se como lo quieren hacer).
> Not found page

- client/src/components/Sidebar/Ordenamientos.jsx
- client/src/components/Sidebar/Sidebar.jsx
- client/src/components/Sidebar/sidebar.module.css
+ ordenamientos en sidebar
+ boton en para borrar ordenamientos
> Ordenamientos

- api/routes/pets.js
- api/utils/functions.js
+ Cambio de propósito del name pasado por query a la ruta filters. Antes buscaba las mascotas que en su nombre incluian name, ahora busca las fundaciones/donantes/givers que incluyen name.
> search combinable con filtros y ordenamiento

- client/src/components/AllCards/AllCards.jsx
Elimine algunas lineas de codigo que estaban doble en el componente AllCards
> actualizacion del front

- client/package-lock.json
- client/package.json
- client/src/components/LoginButton/LoginButton.jsx
- client/src/components/LoginButton/LoginButton.module.css
- client/src/components/LogoutButton/LogoutButton.jsx
- client/src/components/LogoutButton/LogoutButton.module.css
- client/src/components/NavBar/NavBar.jsx
- client/src/index.js
Se agregó el login de usuario. 
Permite loguear con mail y contraseña, a traves de google, Facebook, LinkedIn y Twitter y esa parte ya esta funcional aunque todavia no se conecta con el back y no guarda los datos en la DB.
> login agregado

- api/models/Pet.js
- api/utils/functions.js
- client/src/components/Sidebar/Sidebar.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> Rama filtros

- client/src/components/Landing/Landing.jsx
- client/src/components/Landing/landing.module.css
cambié el estilo de los iconos ya que al ponerles los links se modificaba
> links redes landingPage

- client/src/components/AllCards/AllCards.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/Sidebar/Ordenamientos.jsx
- client/src/components/Sidebar/Sidebar.jsx
- client/src/components/Sidebar/handlersSideBar.js
+ Sort y Search de la ruta adoptar que se complementan a los filtros.
Obs: Por el momento el search recibe el nombre de un usuario y devuelve las mascotas que tienen como dueño un usuario que el nombre este contenido en el nombre ingresado. Estoy al tanto de que es un search rebuscado y por eso hay que organizarnos que vamos a hacer con eso, por otro lado, esta todo funcional y cumpliendo los requisitos mínimos del pi en cuanto a filtrado, busqueda y ordenamiento .
> search, sort y filters funcionando en conjunto

- api/index.js
- client/src/App.js
- client/src/components/Campaigns/Campaigns.jsx
- client/src/components/Campaigns/Campaing.jsx
- client/src/components/Campaigns/DetailCampaign.jsx
- client/src/components/Home/Home.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Agrego componente Campañas (/campañas) y detalle de Campañas (/campañas/:id) (faltan los estilos nada más)
> Campaigns mel

- api/controllers/petControllers.js
- client/src/components/Card/Card.jsx
+ Dueño en cards.
+ En la petición a ruta pets trae nombre del dador/giver.
- Faltan estilos
> dador agregado a la card

- client/src/components/Sidebar/Sidebar.jsx
> fix crash Sidebar

- api/index.js
- client/src/components/AllCards/AllCards.jsx
- client/src/components/Sidebar/Ordenamientos.jsx
- client/src/components/Sidebar/Sidebar.jsx
Versión estable en cuanto a funcionamiento falta algo de estilos.
> demo 1.0.0

- client/src/components/AllCards/AllCards.jsx
- client/src/components/AllCards/allcards.module.css
- client/src/components/Card/Card.jsx
- client/src/components/Card/card.module.css
- client/src/components/Footer/footer.module.css
- client/src/components/Paginado/paginado.module.css
- client/src/components/Sidebar/Ordenamientos.jsx
- client/src/components/Sidebar/Sidebar.jsx
- client/src/components/Sidebar/handlersSideBar.js
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
El footer ya aparece como corresponde
Sé modificó el área de link en la tarjeta para que no entre aun cuando se toca fuera de la visual.
Sé unifico la eliminación de filtro y ordenamientos
Sé ordenó el display de las cards
se agregó la paginacion a estado global y cada vez que se filtra va a la pagina 1
homogenización del paginado con el estilo de la web
footer fix visual en paginas con pocas cards(generalmente la ultima)
> fixes varios

- client/src/components/AllCards/AllCards.jsx
- client/src/components/Sidebar/sidebar.module.css
+ sidebar responsive y ajustado.
antes:
ahora:
+ 8 cards por página
antes:
ahora:
> styles fixes (sidebar y cards)

- api/controllers/petControllers.js
+ cuando se posteaba una mascota se generaba un bucle infinito.
> demo1 : v1.1.0

- client/src/components/AdoptionForm/AdoptionForm.jsx
- client/src/components/AdoptionForm/adoptionForm.module.css
Ahora cuando se ingrese a la ruta /PublicarAdopcion , el boton de dar en adopcion se encontrara deshabilitado hasta que el usuario halla llenado todos los campos. 
Una vez llenado todos los campos el boton cambiara su color y permitira enviar la informacion de la mascota que desea dar en adopcion
> Se agrego la deshabilitacion del boton para dar en adopcion una mascota hasta que se llene todos los campos

- client/src/components/AdoptionForm/AdoptionForm.jsx
Se valida la subida de la imagen en el formulario
> Validation imagen(Formulario)

- client/src/components/AdoptionForm/AdoptionForm.jsx
- client/src/components/Campaigns/Campaigns.jsx
- client/src/components/Campaigns/Campaing.jsx
- client/src/components/Campaigns/campaign.module.css
- client/src/components/Campaigns/campaigns.module.css
- client/src/components/Card/card.module.css
- client/src/components/NavBar/navBar.module.css
se le dio algo de estilo a las campañas, falta terminar
> fix campaings

- client/src/components/Home/Home.jsx
- client/src/components/NavBar/NavBar.jsx
+ Cambio del contenido del botón eliminar busqueda.
+ Eliminación de botón repetido.
antes:
ahora:
> cambios home y navBar

- client/src/components/Campaigns/DetailCampaign.jsx
- client/src/components/Campaigns/campaigns.module.css
- client/src/components/CardDetail/CardDetail.jsx
Se modifico la estructura del componente DetailCampaign.
Se agregaron estilos.
> Detail campaign

- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/NavBar/NavBar.jsx
+ Se mejora el ruteo de algunos botones (search del buscador de mascotas por org y volver de detailCards)
> demo 1.1.1 (version presentada)

- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/Home/Home.jsx
- client/src/components/MapView/MapView.jsx
*Coordenadas funcionales (se ve el mapa de arg)
*Comento el mapa de detail, así no rompe el detalle de la card de pet (después lo coloco donde iría así no rompe)
> Coord funcionales, y comento el mapa de detail

- client/src/components/Home/home.module.css
- client/src/components/LogoutButton/LogoutButton.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/NavBar/navBar.module.css
Agregando menu responsive para cuando se le da click a la foto del usuario una vez iniciada sesion con las opciones de editar perfil y cerrar sesion.
> agregando menu desplegable a la navbar

- client/src/components/Home/home.module.css
Solucionando el problema de superposicion de la imagen del perrito con los botones.
> solucionando problema de la imagen de home

- api/index.js
- api/package-lock.json
- api/package.json
- client/package-lock.json
- client/package.json
- client/src/components/Mensajeria/Mensajeria.jsx
- client/src/components/Mensajeria/RenderizarMensajes.jsx
- client/src/components/Mensajeria/mensajeria.module.css
- client/src/components/NavBar/NavBar.jsx
+ Chat en vivo funcional. avisar si encuentran algun bug.
> Chat terminado

- client/src/components/DashBoardAdm/DashBoardAdm.jsx
- client/src/components/DashBoardAdm/EditCampaign.jsx
- client/src/components/DashBoardAdm/EditPet.jsx
- client/src/components/DashBoardAdm/EditProfile.jsx
- client/src/redux/actions/index.js
Solo faltaria validaciones en el edit profile y estilizados
> Dashboard Adm update

- api/controllers/donationsControllers.js
- api/db.js
- api/routes/donations.js
- client/src/components/Gratitude/Gratitude.jsx
+ cuando se realiza una donación desde el front se guarda en la tabla donations el id del usuario que donó, el id de la campaña a la que el usuario donó, el monto de lo que el usuario donó y el estado de la operación. redacción a marzo
> datos de mp a la base de datos

- api/controllers/messageControllers.js
- api/package.json
- api/routes/message.js
- api/utils/functions.js
- client/src/App.js
- client/src/components/Mensajeria/Mensajeria.jsx
- client/src/components/Mensajeria/RenderizarChats.jsx
- client/src/components/Mensajeria/RenderizarMensajes.jsx
- client/src/components/Mensajeria/mensajeria.module.css
- client/src/components/NavBar/NavBar.jsx
> historial de mensajes agregado y chat estilizado

- api/controllers/messageControllers.js
- api/utils/data.js
- client/src/components/Mensajeria/Mensajeria.jsx
- client/src/components/Mensajeria/RenderizarChats.jsx
- client/src/components/Mensajeria/RenderizarMensajes.jsx
- client/src/components/Mensajeria/mensajeria.module.css
Falta conectar socket.io al historial
Falta responsive pantallas menores a 650px de ancho
> Estilizado y Rutas protegidas del chat

- client/src/components/DashBoardAdm/DashBoardAdm.jsx
- client/src/components/DashBoardAdm/DetailCampaign.jsx
- client/src/components/DashBoardAdm/DetailCampaign.module.css
- client/src/components/DashBoardAdm/DetailPet.jsx
- client/src/components/DashBoardAdm/DetailPet.module.css
- client/src/components/DashBoardAdm/DetailProfile.jsx
- client/src/components/DashBoardAdm/DetailProfile.module.css
- client/src/components/DashBoardAdm/EditCampaign.jsx
- client/src/components/DashBoardAdm/EditCampaign.module.css
- client/src/components/DashBoardAdm/EditPet.jsx
- client/src/components/DashBoardAdm/EditPet.module.css
- client/src/components/DashBoardAdm/EditProfile.jsx
- client/src/components/DashBoardAdm/EditProfile.module.css
- client/src/components/DashBoardAdm/dashBoardAdm.module.css
> dashboard adm estilizado

- api/routes/donations.js
- client/src/components/DashBoardAdm/DashBoardAdm.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Se agrego la tabla donaciones al dashboard adm. Aun falta hacer alguna pruebas de funcionamiento
> dashboard adm table donations added

- client/src/components/Mensajeria/Mensajeria.jsx
- client/src/components/Mensajeria/mensajeria.module.css
- client/src/components/NavBar/NavBar.jsx
> responsive chat

- api/controllers/followControllers.js
- api/routes/follow.js
- api/routes/index.js
- client/src/App.js
- client/src/components/Card/Card.jsx
- client/src/components/Card/card.module.css
- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/NavBar/NavBar.jsx
- client/src/components/NavBar/RenderFavorites.jsx
- client/src/components/NavBar/navBar.module.css
- client/src/components/Paginado/Paginado.jsx
> Favoritos terminado

- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/MapView/MapView.jsx
> mapa con coords funcionaleees yey

- api/utils/data.js
- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/MapView/MapView.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
*se agregaron latitudes y longitudes a los usuarios
*se fixeo el bug donde el mapa quedaba trabado en el pet anterior
*se sacaron varios clg
> fix MapView

- client/src/components/CardDetail/CardDetail.jsx
+ no se renderizaba el laik en detail/:id si lo ponias en otra ruta
+ también se agregó el pop up si das laik en detail/:id y no iniciaste sesion
> bug favoritos arreglado

- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/Footer/Footer.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Mostraba la anterior mascota por un segundo
> bug de detail de mascotas arreglado

- client/src/components/UserDetail/UserDetail.jsx
> se agrego boton para contactar usuario por chat

- api/controllers/adoptionControllers.js
- api/db.js
- api/routes/adoption.js
- api/routes/index.js
- client/src/components/CampaignForm/CampaignForm.jsx
- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/Profile/RenderEnAdopcion.jsx
- client/src/components/UserDetail/UserDetail.jsx
+ back de adopciones
* ruta post a /adoption/solicitud/:SolicitanteId/:MascotaId relaciona el usuario con solicitanteId y la mascota con Mascota Id a través de la tabla intermedia solicitantes.
* ruta get a /adoption/solicitud/:MascotaId trae, en un arreglo, el nombre y el id de los usuarios que estan relacionados con la mascota que tiene MascotaId a través de la tabla intermedia solicitantes.
* ruta post a /adoption/:AdoptanteId/:MascotaId que relaciona el usuario con la mascota a través de la relacion adoptante y setea el atributo adopted de la mascota en "si".
+ formulario de campañas relaciona la campaña con el usuario que la publicó al momento de publicarla.
+ front de adopciones
* cuando se hace click en contactar en la ruta del detalle de las mascotas se relaciona a la mascota con …
> Adopciones

- client/src/components/CardDetail/CardDetail.jsx
- client/src/components/Profile/Profile.jsx
- client/src/components/Profile/RenderAdoptados.jsx
- client/src/components/Profile/RenderCampaigns.jsx
- client/src/components/Profile/RenderDonations.jsx
- client/src/components/Profile/RenderEnAdopcion.css
- client/src/components/Profile/RenderEnAdopcion.jsx
- client/src/components/Profile/profile.css
- client/src/redux/actions/index.js
aaa lptm lo que renegue me quiero volver changos. 
aca se puede apreciar el responsivo: 
aca intento mostrar las funcionalidades:
https://user-images.githubusercontent.com/111701483/220847312-e8416810-567a-4533-977d-0335e6cf594c.mp4
> profile full responsive y full funcionalidades

- client/src/components/CampaignForm/CampaignForm.jsx
- client/src/components/CampaignForm/campaignForm.module.css
Literalmente responsive al formCampaign 🫠
> responsive a formulario de campaña

- client/src/components/ProfileSideBar/ProfileSideBar.jsx
- client/src/components/ProfileSideBar/profileSideBar.module.css
**_Creo tener el gusto de hacer el ultimo pr a develop_**🥹
> Sidebar general
